export const initialFormData = {
    agentName: '',
    agent_id: null,
    propertyAddress: '',
    address_id: null,
    reportDate: '',
    electricalSafetyCheck: false,
    smokeSafetyCheck: false,
    installationExtent: {
        'Main Switchboard': false,
        'Other living areas': false,
        'Main earthing system': false,
        'Laundry': false,
        'Kitchen': false,
        'Garage': false,
        'Bathroom (main)': false,
        'Solar/battery system': false,
        'Other bathrooms/ensuites': false,
        'Installation - Electric water heater': false,
        'Bedroom (main)': false,
        'Installation - Dishwasher': false,
        'Other bedrooms': false,
        'Installation - Electric room/space heaters': false,
        'Living room': false,
        'Installation - Swimming pool equipment': false,
    },
    visualInspection: {
        'Visual - Consumers mains': false,
        'Visual - Space heaters': false,
        'Visual - Switchboards': false,
        'Visual - Cooking equipment': false,
        'Visual - Exposed earth electrode': false,
        'Visual - Dishwasher': false,
        'Visual - Metallic water pipe bond': false,
        'Visual - Exhaust fans': false,
        'Visual - RCDs (Safety switches)': false,
        'Visual - Celling fans': false,
        'Visual - Circuit protection (circuit breakers/fuses)': false,
        'Visual - Washing machinedryer/': false,
        'Visual - Socket-outlets': false,
        'Visual - Installation wiring': false,
        'Visual - Light fittings': false,
        'Visual - Solar and other renewable systems': false,
        'Visual - Electric water heater': false,
        'Visual - Swimming pool equipment': false,
        'Visual - Air conditioners': false,
        'Visual - Vehicle chargers': false,
    },
    polarityTesting: {
        'Polarity - Consumers mains': false,
        'Polarity - Electric water heater': false,
        'Polarity - Circuit protection (circuit breakers/fuses)': false,
        'Polarity - Air conditioners': false,
        'Polarity - RCDs (Safety switches)': false,
        'Polarity - Cooking equipment': false,
        'Polarity - Dishwasher': false,
        'Polarity - Circuit protection (circuit breakers/fuses) (D2)': false,
        'Polarity - Solar and other renewable systems': false,
        'Polarity - Socket-outlets': false,
        'Polarity - Swimming pool equipment': false,
        'Polarity - Vehicle chargers': false,
    },
    earthContinuityTesting: {
        'Earth - Mains earth conductor': false,
        'Earth - Electric water heater': false,
        'Earth - Metallic water pipe bond': false,
        'Earth - Air conditioners': false,
        'Earth - Socket-outlets': false,
        'Earth - Cooking equipment': false,
        'Earth - Light fittings': false,
        'Earth - Dishwasher': false,
        'Earth - Exhaust fans': false,
        'Earth - Solar and other renewable systems': false,
        'Earth - Celling fans': false,
        'Earth - Swimming pool equipment': false,
        'Earth - Vehicle chargers': false,
    },
    rcdTestingPassed: false,
    smokeAlarmsWorking: false,
    nextSmokeAlarmCheckDate: '',
    smokeAlarmDetails: [],
    observation: '',
    recommendation: '',
    images: [],
    electricalSafetyCheckCompletedBy: '',
    licenceNumber: '',
    inspectionDate: '',
    nextInspectionDueDate: '',
    signatureDate: '',
};

// Simple test to verify the utility (for development only)
if (typeof window !== 'undefined') {
  if (initialFormData && typeof initialFormData === 'object' && 'propertyAddress' in initialFormData) {
    console.log('[CheckHero] initialFormData utility loaded and structure looks correct.');
  } else {
    console.error('[CheckHero] initialFormData utility structure is invalid!');
  }
}

export const generateFormPayload = (formType) => (payload) => ({ formType, ...payload });